### ISSUE TITLE
new build of docker image throws error on rasterio import

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/notebooks#105]
I am running docker for mac, which no longer provides `docker-machine`, the tool I was using to set my machine and build the docker images. When I rebuilt the docker image using docker for mac's default virtualization, I ran into the following error on rasterio import:

```
>$docker run -it planet-notebooks python -c "import rasterio"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/rasterio/__init__.py", line 22, in <module>
    from rasterio._base import gdal_version
ImportError: libpoppler.so.76: cannot open shared object file: No such file or directory
```

**Comment by jreiberkyle** [comment]
I traced this to gdal being installed using the conda defaults channel, not the (specified) conda-forge channel. Evidence:

```
>$docker run -it planet-notebooks conda list gdal
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
gdal                      3.0.2            py37hbb2a789_0    defaults
libgdal                   3.0.2                h27ab9cc_0    defaults
```

I have changed the conda install line in `Dockerfile` from
```
RUN conda install -y -c conda-forge --file /tmp/requirements.txt
```
to
```
RUN conda config --set channel_priority strict && \
    conda install -y -c conda-forge --file /tmp/requirements.txt
```

Now gdal is installed from the conda-forge channel
```
>4docker run -it planet-notebooks conda list gdal
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
gdal                      3.0.4            py37hbb6b9fb_1    conda-forge
libgdal                   3.0.4                h022d3c0_1    conda-forge
```
No error is thrown when I run
```
docker run -it planet-notebooks:try2 python -c "import rasterio"
```
